version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      arrow:
        applies-to: version-updates
        patterns:
          - "arrow*"
      geoarrow:
        applies-to: version-updates
        patterns:
          - "geoarrow*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
